# Production environment

services:
  gateway:
    image: caddy:2-alpine
    volumes: [caddy_data:/data, caddy_config:/config]
    ports: [80:80, 443:443]
    configs: [{ source: caddy, target: /etc/caddy/Caddyfile }]
    restart: unless-stopped

  frontend:
    image: ghcr.io/clayenkitten/itam-edu-frontend:main
    build: &build
      dockerfile: ./packages/frontend/Dockerfile
      context: .
    expose: [3000]
    env_file: ./.env
    restart: unless-stopped

  api:
    image: ghcr.io/clayenkitten/itam-edu-api:main
    build: { <<: *build, dockerfile: ./packages/api/Dockerfile }
    depends_on: { db-migration: { condition: service_completed_successfully } }
    expose: [3000]
    env_file: ./.env
    environment: { ITAM_EDU_API_PORT: "3000" }
    restart: unless-stopped

  telegram:
    image: ghcr.io/clayenkitten/itam-edu-telegram:main
    build: { <<: *build, dockerfile: ./packages/telegram/Dockerfile }
    expose: [3000]
    env_file: ./.env
    restart: unless-stopped

  # Database
  ## PostgreSQL server
  postgres:
    image: postgres:17
    expose: [5432]
    ports: [127.0.0.1:5432:5432]
    shm_size: 128mb
    restart: unless-stopped
    volumes: [postgres:/var/lib/postgresql/data]
    env_file: ./.env.db
    healthcheck:
      test: pg_isready --dbname="$$POSTGRES_DB" --username="$$POSTGRES_USER"
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s
      start_interval: 500ms
  ## Database migration
  db-migration:
    image: ghcr.io/clayenkitten/itam-edu-db:main
    build: ./packages/db
    depends_on: { postgres: { condition: service_healthy } }
    env_file: ./.env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # Redis
  redis:
    image: redis:8.0
    entrypoint: sh -c 'redis-server --save 60 1 --appendonly yes --loglevel notice --requirepass $$REDIS_PASSWORD'
    expose: [6379]
    ports: [127.0.0.1:6379:6379]
    restart: unless-stopped
    volumes: [redis:/root/redis]
    env_file: ./.env.db

configs:
  caddy: { file: ./Caddyfile }

volumes:
  postgres:
  redis:
  caddy_data:
  caddy_config:
