version: "3"

silent: true

tasks:
  default:
    cmds: [task --list]

  format:
    desc: Format the whole project
    cmd: npm run format

  check:
    desc: Check code in all packages
    cmd: npm run check --workspaces --if-present

  db:up:
    desc: Run database migrations
    dir: ./packages/db
    cmds:
      - npx dbmate  --no-dump-schema --url "$ITAM_EDU_API_DB_CONNECTION_STRING" --migrations-dir="./migrations" up --strict
      - task: db:codegen

  db:down:
    desc: Revert database migration
    dir: ./packages/db
    cmds:
      - npx dbmate  --no-dump-schema --url "$ITAM_EDU_API_DB_CONNECTION_STRING" --migrations-dir="./migrations" down
      - task: db:codegen

  db:new:
    desc: Create new migration file. Name must be specified as argument.
    dir: ./packages/db
    env:
      DBMATE_MIGRATIONS_DIR: "./migrations"
    cmd: "npx dbmate new -- {{.CLI_ARGS}}"

  db:codegen:
    desc: Generate types from database
    dir: ./packages/db
    cmd: npx kysely-codegen --url "$ITAM_EDU_API_DB_CONNECTION_STRING" --out-file ./index.ts --camel-case --dialect postgres
