# Development environment

services:
  devcontainer:
    build: .
    volumes:
      - ..:/itam-edu:cached
      - .bashrc:/root/.bashrc
    expose:
      - 3000 # DevTools
      - 5150 # Frontend
      - 5151 # Backend
    env_file: [../.env, .env.dev]

  gateway:
    image: caddy:2-alpine
    ports: [127.0.0.1:80:80, 127.0.0.1:443:443]
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  # Databases
  ## PostgreSQL server
  postgres:
    image: postgres:17
    expose: [5432]
    shm_size: 128mb
    volumes: [postgres:/var/lib/postgresql/data]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready --dbname="$$POSTGRES_DB" --username="$$POSTGRES_USER"
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s
      start_interval: 500ms

  ## Redis server
  redis:
    image: redis:8.0
    command: redis-server --save 60 1 --appendonly yes --loglevel warning --requirepass password
    expose: [6379]
    volumes: [redis:/data]

  ## Minio
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    entrypoint: sh -c "mc mb /data/files --ignore-existing && minio server --console-address ":9001" /data"
    expose: ["9000", "9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Web interface for databases
  dbgate:
    image: dbgate/dbgate:6.4.1-alpine
    expose: [3000]
    environment:
      CONNECTIONS: Postgres,Redis

      LABEL_Postgres: Postgres
      ENGINE_Postgres: postgres@dbgate-plugin-postgres
      SERVER_Postgres: postgres
      PORT_Postgres: 5432
      DATABASE_Postgres: app
      USER_Postgres: user
      PASSWORD_Postgres: password

      LABEL_Redis: Redis
      ENGINE_Redis: redis@dbgate-plugin-redis
      SERVER_Redis: redis
      PORT_Redis: 6379
      DATABASE_Redis: 0
      USER_Redis: default
      PASSWORD_Redis: password
    volumes:
      - dbgate:/root/.dbgate

  # BullMQ UI
  bull-board:
    # image: venatum/bull-board:2.2
    build: https://github.com/ClayenKitten/bull-board-docker.git#host
    restart: unless-stopped
    expose: [3000]
    environment:
      HOST: 0.0.0.0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: password

volumes:
  postgres:
  redis:
  minio:
  dbgate:
  caddy_data:
  caddy_config:
