# Development environment

services:
  devcontainer:
    build: .
    volumes:
      - ..:/itam-edu:cached
      - .bashrc:/root/.bashrc
    expose:
      - 3000 # DevTools
      - 5150 # Frontend
      - 5151 # Backend
      - 5152 # Files
    env_file: [../.env, .env.dev]

  gateway:
    image: caddy:2-alpine
    ports: [127.0.0.1:80:80, 127.0.0.1:443:443]
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  postgres:
    image: postgres:17
    expose: [5432]
    shm_size: 128mb
    volumes: [postgres:/var/lib/postgresql/data]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready --dbname="$$POSTGRES_DB" --username="$$POSTGRES_USER"
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 30s
      start_interval: 500ms

  redis:
    image: redis:8.0
    restart: unless-stopped
    command: redis-server --save 60 1 --appendonly yes --loglevel warning --requirepass password
    expose: [6379]
    volumes: [redis:/data]

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    entrypoint: sh -c "mc mb /data/files --ignore-existing && mc mb /data/recordings --ignore-existing && minio server --console-address ":9001" /data"
    expose: ["9000", "9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  livekit:
    image: livekit/livekit-server:v1.9.1
    entrypoint:
      - /bin/sh
      - -c
      - /livekit-server --config /etc/livekit.yaml --bind 0.0.0.0 --node-ip "$$LIVEKIT_NODE_IP"
    env_file: [../.env, .env.dev]
    restart: unless-stopped
    ports:
      - 7880:7880 # API
      - 7881:7881 # WebRTC over TCP (fallback)
      - 52012:52012/udp # TURN UDP
      - 56001-56010:56001-56010/udp # WebRTC
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

  livekit-egress:
    image: livekit/egress:v1.9.1
    restart: unless-stopped
    volumes:
      - ./livekit-egress.yaml:/etc/egress.yaml
    environment:
      EGRESS_CONFIG_FILE: /etc/egress.yaml

  livekit-ingress:
    image: livekit/ingress:v1.4.3
    restart: unless-stopped
    volumes:
      - ./livekit-ingress.yaml:/etc/ingress.yaml
    environment:
      INGRESS_CONFIG_FILE: /etc/ingress.yaml

  livekit-redis:
    image: redis:8.0
    restart: unless-stopped
    command: redis-server --save 60 1 --appendonly yes --loglevel warning --requirepass password
    expose: [6379]
    volumes: [redis_livekit:/data]

  # Web interface for databases
  dbgate:
    image: dbgate/dbgate:6.4.1-alpine
    expose: [3000]
    environment:
      CONNECTIONS: Postgres,Redis,RedisLivekit

      LABEL_Postgres: Postgres
      ENGINE_Postgres: postgres@dbgate-plugin-postgres
      SERVER_Postgres: postgres
      PORT_Postgres: 5432
      DATABASE_Postgres: app
      USER_Postgres: user
      PASSWORD_Postgres: password

      LABEL_Redis: Redis
      ENGINE_Redis: redis@dbgate-plugin-redis
      SERVER_Redis: redis
      PORT_Redis: 6379
      DATABASE_Redis: 0
      USER_Redis: default
      PASSWORD_Redis: password

      LABEL_RedisLivekit: Redis LiveKit
      ENGINE_RedisLivekit: redis@dbgate-plugin-redis
      SERVER_RedisLivekit: livekit-redis
      PORT_RedisLivekit: 6379
      DATABASE_RedisLivekit: 0
      USER_RedisLivekit: default
      PASSWORD_RedisLivekit: password
    volumes:
      - dbgate:/root/.dbgate

  # BullMQ UI
  bull-board:
    image: venatum/bull-board:2.4
    restart: unless-stopped
    expose: [3000]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: password

volumes:
  postgres:
  redis:
  minio:
  dbgate:
  caddy_data:
  caddy_config:
  redis_livekit:
