name: Build Packages
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      tag: { type: string }
      ref: { type: string }
  workflow_call:
    inputs:
      tag: { type: string }
      ref: { type: string }

jobs:
  build-api:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-api
      tag: "${{ inputs.tag }}"
      context: .
      dockerfile: packages/api/Dockerfile
      ref: ${{ inputs.ref }}

  build-frontend:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-frontend
      tag: "${{ inputs.tag }}"
      context: .
      dockerfile: packages/frontend/Dockerfile
      ref: ${{ inputs.ref }}

  build-files:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-files
      tag: "${{ inputs.tag }}"
      context: .
      dockerfile: packages/files/Dockerfile
      ref: ${{ inputs.ref }}

  build-db:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-db
      tag: "${{ inputs.tag }}"
      context: packages/db
      ref: ${{ inputs.ref }}
