name: Build
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      image: { type: string, required: true }
      context: { type: string, required: true }
      dockerfile: { type: string, default: Dockerfile }
  workflow_call:
    inputs:
      image: { type: string, required: true }
      context: { type: string, required: true }
      dockerfile: { type: string, default: Dockerfile }

jobs:
  docker:
    name: Build and push Docker images
    runs-on: ubuntu-22.04

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "${{ inputs.context }}"
          file: "${{ inputs.context }}/${{ inputs.dockerfile || 'Dockerfile' }}"
          tags: "${{ steps.meta.outputs.tags }}"
          push: true
          cache-from: "type=registry,ref=${{ steps.meta.outputs.tags }}"
          cache-to: "type=inline"
