name: Build Packages
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-api:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-api
      context: .
      dockerfile: packages/api/Dockerfile

  build-frontend:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-frontend
      context: .
      dockerfile: packages/frontend/Dockerfile

  build-db:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-db
      context: packages/db

  build-media:
    uses: "./.github/workflows/build.yaml"
    with:
      image: itam-edu-media
      context: packages/media
