name: Check code
permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install Dependencies
        id: deps
        run: npm ci

      - name: Check
        id: check
        run: "npm run check --if-present --workspaces"
        if: ${{ !cancelled() && steps.deps.conclusion == 'success' }}

      - name: Test
        run: "npm run test --if-present --workspaces"
        if: ${{ !cancelled() && steps.check.conclusion == 'success' }}
