name: Format
permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  format:
    name: Format
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install Dependencies
        id: deps
        run: npm ci --workspaces=false

      - name: Check formatting
        run: "npm run check:format --if-present --workspaces"
        continue-on-error: ${{ github.event_name != 'pull_request' }}
