name: Main workflow
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare
    uses: "./.github/workflows/prepare.yaml"

  check:
    name: Check
    uses: "./.github/workflows/check.yaml"

  pipeline:
    name: Package pipeline
    uses: "./.github/workflows/pipeline.yaml"
    needs: [prepare, check]
    if: ${{ success() && needs.prepare.outputs.services != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.prepare.outputs.docker-services) }}
      fail-fast: false
    with:
      service: "${{ toJson(matrix.service) }}"

  report:
    name: Report
    uses: "./.github/workflows/report.yaml"
    needs: pipeline
    if: ${{ !cancelled() }}
    secrets:
      chat: "${{ secrets.TELEGRAM_REPORT_CHAT }}"
      token: "${{ secrets.TELEGRAM_REPORT_TOKEN }}"
