name: Main workflow
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  check-code:
    uses: "./.github/workflows/check-code.yaml"

  check-format:
    uses: "./.github/workflows/check-format.yaml"

  check-db:
    uses: "./.github/workflows/check-db.yaml"

  build:
    uses: "./.github/workflows/build-packages.yaml"
    needs: [check-code, check-format, check-db]
