name: Main workflow
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [main]

jobs:
  format:
    name: Check Format
    uses: "./.github/workflows/format.yaml"

  check:
    name: Check Code
    uses: "./.github/workflows/check.yaml"

  prepare:
    name: Prepare Services
    uses: "./.github/workflows/prepare.yaml"
    needs: [format, check]

  build:
    name: Build
    uses: "./.github/workflows/build.yaml"
    needs: [prepare]
    if: ${{ success() && needs.prepare.outputs.services != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.prepare.outputs.docker-services) }}
      fail-fast: false
    with:
      image: ${{ toJson(matrix.service).docker.name }}
      context: ${{ toJson(matrix.service).docker.context }}
      dockerfile: ${{ toJson(matrix.service).docker.dockerfile }}
