name: Pipeline
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      service: { type: string, required: true }
  workflow_call:
    inputs:
      service: { type: string, required: true }

jobs:
  check:
    name: Check
    if: ${{ contains(fromJson(inputs.service).kind, 'node') }}
    uses: "./.github/workflows/check.yaml"
    with:
      path: ./packages/${{ fromJson(inputs.service).name }}

  build:
    name: Build
    needs: check
    if: ${{ !cancelled() && needs.check.result != 'failure' }}
    uses: "./.github/workflows/build.yaml"
    with:
      image: ${{ fromJson(inputs.service).name }}
      context: ./packages/${{ fromJson(inputs.service).name }}

  report:
    name: Report pipeline result
    needs: [check, build]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo '✅ itam-edu-${{ fromJson(inputs.service).name }}' > summary.txt
        if: ${{ needs.build.result == 'success' }}
      - run: echo '🚫 itam-edu-${{ fromJson(inputs.service).name }}' > summary.txt
        if: ${{ needs.build.result == 'failure' || needs.check.result == 'failure' }}
      - uses: actions/upload-artifact@v4
        with:
          name: "summary-${{ fromJson(inputs.service).name }}"
          path: "summary.txt"
