name: Pull Request workflow
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    name: Check Code
    uses: "./.github/workflows/check.yaml"

  check-format:
    name: Check Format
    uses: "./.github/workflows/format.yaml"

  check-db:
    name: Check Database
    uses: "./.github/workflows/check-db.yaml"
