name: Main workflow
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  pull_request:

jobs:
  format:
    name: Check Format
    uses: "./.github/workflows/format.yaml"

  check:
    name: Check Code
    uses: "./.github/workflows/check.yaml"
