name: Pull Request workflow
permissions:
  contents: read
  packages: write

on:
  pull_request:

jobs:
  check-code:
    uses: "./.github/workflows/check-code.yaml"

  check-format:
    uses: "./.github/workflows/check-format.yaml"

  check-db:
    uses: "./.github/workflows/check-db.yaml"
